theme: jekyll-theme-cayman
lang: de
baseurl: /adapter
title:
  de: eBUS Adapter 2.0
  en: eBUS adapter 2.0
description:
  de: Hardware-Adapter zur Kommunikation mit eBUS Heizsystemen
  en: Hardware interface for communicating with eBUS heating system
github:
  is_project_page: false

